apiVersion: v1
kind: Secret
metadata:
  name: iq-webhook-secret
  namespace: iq-webhook-listener
type: Opaque
stringData:
  MESSENGER_URL: "http://your-messenger-url"
  SRV_CODE: "SRV_CODE"
  RECIPIENT: "RECEIVER"
  SAVEOPTION: "N"
  SENDER_ALIAS: "SYSTEM"