apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iq-webhook-listener-ingress
  namespace: iq-webhook-listener
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: webhook.192.168.41.90.sslip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: iq-webhook-listener
            port:
              number: 3000