apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iq-webhook-listener.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
